// ROUTING
export const SET_ROUTE = "SET_ROUTE";

// SETTINGS
export const UPDATE_SETTINGS = "UPDATE_SETTINGS";

// CATEGORIES
export const SET_CATEGORIES = "SET_CATEGORIES";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";

// GAME SETUP
export const SET_GAME_DRAFT = "SET_GAME_DRAFT";
export const UPDATE_PLAYER_COUNT = "UPDATE_PLAYER_COUNT";
export const UPDATE_IMPOSTOR_COUNT = "UPDATE_IMPOSTOR_COUNT";
export const UPDATE_PLAYER_NAME = "UPDATE_PLAYER_NAME";
export const TOGGLE_CATEGORY = "TOGGLE_CATEGORY";

// GAMEPLAY
export const START_GAME = "START_GAME";
export const REVEAL_CURRENT_PLAYER = "REVEAL_CURRENT_PLAYER";
export const FINISH_REVEAL_PHASE = "FINISH_REVEAL_PHASE";
export const SET_GAME_PHASE = "SET_GAME_PHASE";
export const NEXT_PLAYER = "NEXT_PLAYER";
export const VOTE_PLAYER = "VOTE_PLAYER";
export const REVEAL_IMPOSTORS = "REVEAL_IMPOSTORS";
export const RESET_GAME = "RESET_GAME";

// HYDRATION
export const HYDRATE_STATE = "HYDRATE_STATE";
